service: ${self:custom.SERVICE_NAMESPACE}

custom:
  stages:
    - tst
    - prd
  SERVICE_NAMESPACE: ${opt:STAGE, 'prd'}-sls-api
  DB_CONNECTION_URI: ${env:DB_CONNECTION_URI}
  AWS_REGION_NAME: us-east-1
  # set this variable on your ENVIRONMENTS
  # DB_CONNECTION_URI: mongodb+srv://USER_HERE:PASSWORD_HERE@yourhost.net/DATABASENAME?retryWrites=true&w=majority

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${self:custom.AWS_REGION_NAME}
  environment: ${file(env.${opt:STAGE, 'prd'}.yml)}

functions:
  - ${file(src/routes/users.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-tscpaths
